deps_config := \
	/home/mrnam/bot121_vbluno51_zephyr-os/boards/arm/nrf51_vbluno51/Kconfig.defconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/boards/arm/nrf52_vbluno52/Kconfig.defconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/arch/arm/soc/ti_simplelink/cc32xx/Kconfig.defconfig.cc3200 \
	/home/mrnam/bot121_vbluno51_zephyr-os/arch/arm/soc/ti_simplelink/cc32xx/Kconfig.defconfig.cc3220sf \
	/home/mrnam/bot121_vbluno51_zephyr-os/arch/arm/soc/ti_simplelink/cc2650/Kconfig.defconfig.series \
	/home/mrnam/bot121_vbluno51_zephyr-os/arch/arm/soc/ti_simplelink/cc32xx/Kconfig.defconfig.series \
	/home/mrnam/bot121_vbluno51_zephyr-os/arch/arm/soc/st_stm32/stm32l4/Kconfig.defconfig.stm32l432xx \
	/home/mrnam/bot121_vbluno51_zephyr-os/arch/arm/soc/st_stm32/stm32l4/Kconfig.defconfig.stm32l475xg \
	/home/mrnam/bot121_vbluno51_zephyr-os/arch/arm/soc/st_stm32/stm32l4/Kconfig.defconfig.stm32l476xx \
	/home/mrnam/bot121_vbluno51_zephyr-os/arch/arm/soc/st_stm32/stm32l4/Kconfig.defconfig.stm32l496xx \
	/home/mrnam/bot121_vbluno51_zephyr-os/arch/arm/soc/st_stm32/stm32f4/Kconfig.defconfig.stm32f401xe \
	/home/mrnam/bot121_vbluno51_zephyr-os/arch/arm/soc/st_stm32/stm32f4/Kconfig.defconfig.stm32f407xx \
	/home/mrnam/bot121_vbluno51_zephyr-os/arch/arm/soc/st_stm32/stm32f4/Kconfig.defconfig.stm32f411xe \
	/home/mrnam/bot121_vbluno51_zephyr-os/arch/arm/soc/st_stm32/stm32f4/Kconfig.defconfig.stm32f412zg \
	/home/mrnam/bot121_vbluno51_zephyr-os/arch/arm/soc/st_stm32/stm32f4/Kconfig.defconfig.stm32f413xx \
	/home/mrnam/bot121_vbluno51_zephyr-os/arch/arm/soc/st_stm32/stm32f4/Kconfig.defconfig.stm32f429xx \
	/home/mrnam/bot121_vbluno51_zephyr-os/arch/arm/soc/st_stm32/stm32f4/Kconfig.defconfig.stm32f469xi \
	/home/mrnam/bot121_vbluno51_zephyr-os/arch/arm/soc/st_stm32/stm32f3/Kconfig.defconfig.stm32f303xc \
	/home/mrnam/bot121_vbluno51_zephyr-os/arch/arm/soc/st_stm32/stm32f3/Kconfig.defconfig.stm32f334x8 \
	/home/mrnam/bot121_vbluno51_zephyr-os/arch/arm/soc/st_stm32/stm32f3/Kconfig.defconfig.stm32f373xc \
	/home/mrnam/bot121_vbluno51_zephyr-os/arch/arm/soc/st_stm32/stm32f1/Kconfig.defconfig.stm32f103xx \
	/home/mrnam/bot121_vbluno51_zephyr-os/arch/arm/soc/st_stm32/stm32f1/Kconfig.defconfig.stm32f107xc \
	/home/mrnam/bot121_vbluno51_zephyr-os/arch/arm/soc/st_stm32/stm32f1/Kconfig.defconfig.series \
	/home/mrnam/bot121_vbluno51_zephyr-os/arch/arm/soc/st_stm32/stm32f3/Kconfig.defconfig.series \
	/home/mrnam/bot121_vbluno51_zephyr-os/arch/arm/soc/st_stm32/stm32f4/Kconfig.defconfig.series \
	/home/mrnam/bot121_vbluno51_zephyr-os/arch/arm/soc/st_stm32/stm32l4/Kconfig.defconfig.series \
	/home/mrnam/bot121_vbluno51_zephyr-os/arch/arm/soc/nxp_kinetis/kwx/Kconfig.defconfig.mkw40z4 \
	/home/mrnam/bot121_vbluno51_zephyr-os/arch/arm/soc/nxp_kinetis/kwx/Kconfig.defconfig.mkw41z4 \
	/home/mrnam/bot121_vbluno51_zephyr-os/arch/arm/soc/nxp_kinetis/kl2x/Kconfig.defconfig.mkl25z4 \
	/home/mrnam/bot121_vbluno51_zephyr-os/arch/arm/soc/nxp_kinetis/k6x/Kconfig.defconfig.mk64f12 \
	/home/mrnam/bot121_vbluno51_zephyr-os/arch/arm/soc/nxp_kinetis/k6x/Kconfig.defconfig.series \
	/home/mrnam/bot121_vbluno51_zephyr-os/arch/arm/soc/nxp_kinetis/kl2x/Kconfig.defconfig.series \
	/home/mrnam/bot121_vbluno51_zephyr-os/arch/arm/soc/nxp_kinetis/kwx/Kconfig.defconfig.series \
	/home/mrnam/bot121_vbluno51_zephyr-os/arch/arm/soc/nordic_nrf5/nrf52/Kconfig.defconfig.nrf52832_QFAA \
	/home/mrnam/bot121_vbluno51_zephyr-os/arch/arm/soc/nordic_nrf5/nrf52/Kconfig.defconfig.nrf52840_QIAA \
	/home/mrnam/bot121_vbluno51_zephyr-os/arch/arm/soc/nordic_nrf5/nrf51/Kconfig.defconfig.nrf51822_QFAA \
	/home/mrnam/bot121_vbluno51_zephyr-os/arch/arm/soc/nordic_nrf5/nrf51/Kconfig.defconfig.nrf51822_QFAB \
	/home/mrnam/bot121_vbluno51_zephyr-os/arch/arm/soc/nordic_nrf5/nrf51/Kconfig.defconfig.nrf51822_QFAC \
	/home/mrnam/bot121_vbluno51_zephyr-os/arch/arm/soc/nordic_nrf5/nrf51/Kconfig.defconfig.series \
	/home/mrnam/bot121_vbluno51_zephyr-os/arch/arm/soc/nordic_nrf5/nrf52/Kconfig.defconfig.series \
	/home/mrnam/bot121_vbluno51_zephyr-os/arch/arm/soc/atmel_sam/sam3x/Kconfig.defconfig.series \
	/home/mrnam/bot121_vbluno51_zephyr-os/arch/arm/soc/atmel_sam/sam4s/Kconfig.defconfig.series \
	/home/mrnam/bot121_vbluno51_zephyr-os/arch/arm/soc/atmel_sam/same70/Kconfig.defconfig.series \
	/home/mrnam/bot121_vbluno51_zephyr-os/arch/arm/soc/arm/mps2/Kconfig.defconfig.mps2_an385 \
	/home/mrnam/bot121_vbluno51_zephyr-os/arch/arm/soc/arm/beetle/Kconfig.defconfig.beetle_r0 \
	/home/mrnam/bot121_vbluno51_zephyr-os/arch/arm/soc/arm/beetle/Kconfig.defconfig.series \
	/home/mrnam/bot121_vbluno51_zephyr-os/arch/arm/soc/arm/mps2/Kconfig.defconfig.series \
	/home/mrnam/bot121_vbluno51_zephyr-os/arch/arm/soc/arm/Kconfig.defconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/arch/arm/soc/atmel_sam/Kconfig.defconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/arch/arm/soc/nordic_nrf5/Kconfig.defconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/arch/arm/soc/nxp_kinetis/Kconfig.defconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/arch/arm/soc/st_stm32/Kconfig.defconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/arch/arm/soc/ti_lm3s6965/Kconfig.defconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/arch/arm/soc/ti_simplelink/Kconfig.defconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/tests/ztest/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/tests/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/ext/debug/segger/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/ext/debug/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/ext/fs/fat/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/ext/fs/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/ext/lib/crypto/mbedtls/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/ext/lib/crypto/tinycrypt/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/ext/lib/crypto/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/ext/hal/ti/simplelink/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/ext/hal/ti/cc3200sdk/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/ext/hal/st/stm32cube/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/ext/hal/qmsi/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/ext/hal/nxp/mcux/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/ext/hal/nordic/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/ext/hal/cmsis/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/ext/hal/atmel/asf/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/ext/hal/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/ext/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/subsys/shell/modules/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/subsys/shell/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/subsys/debug/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/subsys/logging/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/subsys/net/lib/app/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/subsys/net/lib/http/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/subsys/net/lib/mqtt/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/subsys/net/lib/dns/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/subsys/net/lib/zoap/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/subsys/net/lib/sockets/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/subsys/net/lib/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/subsys/net/ip/Kconfig.stats \
	/home/mrnam/bot121_vbluno51_zephyr-os/subsys/net/ip/Kconfig.rpl \
	/home/mrnam/bot121_vbluno51_zephyr-os/subsys/net/ip/Kconfig.mgmt \
	/home/mrnam/bot121_vbluno51_zephyr-os/subsys/net/ip/l2/ieee802154/Kconfig.radio \
	/home/mrnam/bot121_vbluno51_zephyr-os/subsys/net/ip/l2/ieee802154/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/subsys/net/ip/l2/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/subsys/net/ip/Kconfig.stack \
	/home/mrnam/bot121_vbluno51_zephyr-os/subsys/net/ip/Kconfig.ipv4 \
	/home/mrnam/bot121_vbluno51_zephyr-os/subsys/net/ip/Kconfig.ipv6 \
	/home/mrnam/bot121_vbluno51_zephyr-os/subsys/net/ip/Kconfig.debug \
	/home/mrnam/bot121_vbluno51_zephyr-os/subsys/net/ip/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/subsys/net/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/subsys/disk/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/subsys/console/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/subsys/bluetooth/shell/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/subsys/bluetooth/controller/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/subsys/bluetooth/host/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/subsys/bluetooth/common/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/subsys/bluetooth/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/subsys/usb/class/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/subsys/usb/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/subsys/fs/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/subsys/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/lib/json/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/lib/libc/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/lib/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/misc/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/display/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/crypto/Kconfig.ataes132a \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/crypto/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/usb/device/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/usb/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/dma/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/counter/Kconfig.dtmr_cmsdk_apb \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/counter/Kconfig.tmr_cmsdk_apb \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/counter/Kconfig.qmsi \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/counter/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/sensor/tmp112/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/sensor/tmp007/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/sensor/th02/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/sensor/sx9500/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/sensor/sht3xd/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/sensor/nrf5/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/sensor/mpu6050/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/sensor/mcp9808/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/sensor/max44009/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/sensor/max30101/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/sensor/lsm9ds0_mfd/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/sensor/lsm9ds0_gyro/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/sensor/lsm6dsl/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/sensor/lsm6ds0/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/sensor/lps25hb/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/sensor/lps22hb/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/sensor/lis3mdl/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/sensor/lis3dh/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/sensor/lis2dh/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/sensor/isl29035/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/sensor/hts221/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/sensor/hp206c/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/sensor/hmc5883l/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/sensor/hdc1008/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/sensor/fxos8700/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/sensor/fxas21002/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/sensor/dht/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/sensor/bmi160/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/sensor/bmg160/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/sensor/bme280/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/sensor/bmc150_magn/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/sensor/bma280/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/sensor/ak8975/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/sensor/adxl362/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/sensor/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/flash/Kconfig.stm32 \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/flash/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/aio/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/ipm/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/clock_control/Kconfig.beetle \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/clock_control/Kconfig.stm32 \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/clock_control/Kconfig.quark_se \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/clock_control/Kconfig.nrf5 \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/clock_control/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/watchdog/Kconfig.sam \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/watchdog/Kconfig.cmsdk_apb \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/watchdog/Kconfig.stm32 \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/watchdog/Kconfig.qmsi \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/watchdog/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/rtc/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/adc/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/pinmux/Kconfig.cc2650 \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/pinmux/Kconfig.fe310 \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/pinmux/Kconfig.beetle \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/pinmux/Kconfig.stm32 \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/pinmux/Kconfig.mcux \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/pinmux/dev/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/pinmux/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/pwm/Kconfig.nrf5_sw \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/pwm/Kconfig.stm32 \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/pwm/Kconfig.k64 \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/pwm/Kconfig.dw \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/pwm/Kconfig.qmsi \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/pwm/Kconfig.pca9685 \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/pwm/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/i2c/Kconfig.gpio \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/i2c/Kconfig.sbcon \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/i2c/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/spi/Kconfig.nrf5 \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/spi/Kconfig.mcux_dspi \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/spi/Kconfig.dw \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/spi/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/shared_irq/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/gpio/Kconfig.cc2650 \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/gpio/Kconfig.fe310 \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/gpio/Kconfig.pulpino \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/gpio/Kconfig.cc32xx \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/gpio/Kconfig.cmsdk_ahb \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/gpio/Kconfig.nrf5 \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/gpio/Kconfig.stm32 \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/gpio/Kconfig.atmel_sam3 \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/gpio/Kconfig.mmio32 \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/gpio/Kconfig.mcux \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/gpio/Kconfig.sch \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/gpio/Kconfig.qmsi \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/gpio/Kconfig.pcal9535a \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/gpio/Kconfig.dw \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/gpio/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/pci/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/grove/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/random/Kconfig.mcux \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/random/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/timer/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/interrupt_controller/Kconfig.stm32 \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/interrupt_controller/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/serial/Kconfig.esp32 \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/serial/Kconfig.fe310 \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/serial/Kconfig.riscv_qemu \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/serial/Kconfig.cmsdk_apb \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/serial/Kconfig.cc32xx \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/serial/Kconfig.altera_jtag \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/serial/Kconfig.nrf5 \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/serial/Kconfig.stm32 \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/serial/Kconfig.qmsi \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/serial/Kconfig.uart_sam \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/serial/Kconfig.usart_sam \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/serial/Kconfig.atmel_sam3 \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/serial/Kconfig.nsim \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/serial/Kconfig.stellaris \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/serial/Kconfig.mcux_lpuart \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/serial/Kconfig.mcux_lpsci \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/serial/Kconfig.mcux \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/serial/Kconfig.ns16550 \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/serial/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/slip/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/ethernet/Kconfig.sam_gmac \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/ethernet/Kconfig.dw \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/ethernet/Kconfig.mcux \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/ethernet/Kconfig.enc28j60 \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/ethernet/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/console/Kconfig.telnet \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/console/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/ieee802154/Kconfig.nrf5 \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/ieee802154/Kconfig.mcr20a \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/ieee802154/Kconfig.kw41z \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/ieee802154/Kconfig.cc2520 \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/ieee802154/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/bluetooth/hci/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/bluetooth/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/drivers/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/kernel/Kconfig.power_mgmt \
	/home/mrnam/bot121_vbluno51_zephyr-os/kernel/Kconfig.event_logger \
	/home/mrnam/bot121_vbluno51_zephyr-os/kernel/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/boards/arm/nrf52_vbluno52/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/boards/arm/nrf51_vbluno51/Kconfig.board \
	/home/mrnam/bot121_vbluno51_zephyr-os/boards/arm/nrf52_vbluno52/Kconfig.board \
	/home/mrnam/bot121_vbluno51_zephyr-os/boards/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/arch/arm/soc/ti_simplelink/cc2650/Kconfig.soc \
	/home/mrnam/bot121_vbluno51_zephyr-os/arch/arm/soc/ti_simplelink/cc32xx/Kconfig.soc \
	/home/mrnam/bot121_vbluno51_zephyr-os/arch/arm/soc/st_stm32/stm32f1/Kconfig.soc \
	/home/mrnam/bot121_vbluno51_zephyr-os/arch/arm/soc/st_stm32/stm32f3/Kconfig.soc \
	/home/mrnam/bot121_vbluno51_zephyr-os/arch/arm/soc/st_stm32/stm32f4/Kconfig.soc \
	/home/mrnam/bot121_vbluno51_zephyr-os/arch/arm/soc/st_stm32/stm32l4/Kconfig.soc \
	/home/mrnam/bot121_vbluno51_zephyr-os/arch/arm/soc/nxp_kinetis/k6x/Kconfig.soc \
	/home/mrnam/bot121_vbluno51_zephyr-os/arch/arm/soc/nxp_kinetis/kl2x/Kconfig.soc \
	/home/mrnam/bot121_vbluno51_zephyr-os/arch/arm/soc/nxp_kinetis/kwx/Kconfig.soc \
	/home/mrnam/bot121_vbluno51_zephyr-os/arch/arm/soc/nordic_nrf5/nrf51/Kconfig.soc \
	/home/mrnam/bot121_vbluno51_zephyr-os/arch/arm/soc/nordic_nrf5/nrf52/Kconfig.soc \
	/home/mrnam/bot121_vbluno51_zephyr-os/arch/arm/soc/atmel_sam/sam3x/Kconfig.soc \
	/home/mrnam/bot121_vbluno51_zephyr-os/arch/arm/soc/atmel_sam/sam4s/Kconfig.soc \
	/home/mrnam/bot121_vbluno51_zephyr-os/arch/arm/soc/atmel_sam/same70/Kconfig.soc \
	/home/mrnam/bot121_vbluno51_zephyr-os/arch/arm/soc/arm/beetle/Kconfig.soc \
	/home/mrnam/bot121_vbluno51_zephyr-os/arch/arm/soc/arm/mps2/Kconfig.soc \
	/home/mrnam/bot121_vbluno51_zephyr-os/arch/arm/soc/arm/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/arch/arm/soc/atmel_sam/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/arch/arm/soc/nordic_nrf5/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/arch/arm/soc/nxp_kinetis/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/arch/arm/soc/st_stm32/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/arch/arm/soc/ti_lm3s6965/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/arch/arm/soc/ti_simplelink/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/arch/arm/core/cortex_m/mpu/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/arch/arm/core/cortex_m/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/arch/arm/core/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/arch/arm/soc/ti_simplelink/cc2650/Kconfig.series \
	/home/mrnam/bot121_vbluno51_zephyr-os/arch/arm/soc/ti_simplelink/cc32xx/Kconfig.series \
	/home/mrnam/bot121_vbluno51_zephyr-os/arch/arm/soc/st_stm32/stm32f1/Kconfig.series \
	/home/mrnam/bot121_vbluno51_zephyr-os/arch/arm/soc/st_stm32/stm32f3/Kconfig.series \
	/home/mrnam/bot121_vbluno51_zephyr-os/arch/arm/soc/st_stm32/stm32f4/Kconfig.series \
	/home/mrnam/bot121_vbluno51_zephyr-os/arch/arm/soc/st_stm32/stm32l4/Kconfig.series \
	/home/mrnam/bot121_vbluno51_zephyr-os/arch/arm/soc/nxp_kinetis/k6x/Kconfig.series \
	/home/mrnam/bot121_vbluno51_zephyr-os/arch/arm/soc/nxp_kinetis/kl2x/Kconfig.series \
	/home/mrnam/bot121_vbluno51_zephyr-os/arch/arm/soc/nxp_kinetis/kwx/Kconfig.series \
	/home/mrnam/bot121_vbluno51_zephyr-os/arch/arm/soc/nordic_nrf5/nrf51/Kconfig.series \
	/home/mrnam/bot121_vbluno51_zephyr-os/arch/arm/soc/nordic_nrf5/nrf52/Kconfig.series \
	/home/mrnam/bot121_vbluno51_zephyr-os/arch/arm/soc/atmel_sam/sam3x/Kconfig.series \
	/home/mrnam/bot121_vbluno51_zephyr-os/arch/arm/soc/atmel_sam/sam4s/Kconfig.series \
	/home/mrnam/bot121_vbluno51_zephyr-os/arch/arm/soc/atmel_sam/same70/Kconfig.series \
	/home/mrnam/bot121_vbluno51_zephyr-os/arch/arm/soc/arm/beetle/Kconfig.series \
	/home/mrnam/bot121_vbluno51_zephyr-os/arch/arm/soc/arm/mps2/Kconfig.series \
	/home/mrnam/bot121_vbluno51_zephyr-os/arch/arm/soc/arm/Kconfig.soc \
	/home/mrnam/bot121_vbluno51_zephyr-os/arch/arm/soc/atmel_sam/Kconfig.soc \
	/home/mrnam/bot121_vbluno51_zephyr-os/arch/arm/soc/nordic_nrf5/Kconfig.soc \
	/home/mrnam/bot121_vbluno51_zephyr-os/arch/arm/soc/nxp_kinetis/Kconfig.soc \
	/home/mrnam/bot121_vbluno51_zephyr-os/arch/arm/soc/st_stm32/Kconfig.soc \
	/home/mrnam/bot121_vbluno51_zephyr-os/arch/arm/soc/ti_lm3s6965/Kconfig.soc \
	/home/mrnam/bot121_vbluno51_zephyr-os/arch/arm/soc/ti_simplelink/Kconfig.soc \
	/home/mrnam/bot121_vbluno51_zephyr-os/arch/arm/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/arch/Kconfig \
	/home/mrnam/bot121_vbluno51_zephyr-os/Kconfig.zephyr \
	Kconfig

include/config/auto.conf: \
	$(deps_config)

ifneq "$(KERNELVERSION)" "1.8.99"
include/config/auto.conf: FORCE
endif

$(deps_config): ;
